// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TP1___GRUPO_C.Modelos;

#nullable disable

namespace TP1___GRUPO_C.Migrations
{
    [DbContext(typeof(MyContext))]
    partial class MyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TP1___GRUPO_C.Model.Funcion", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("AsientosDisponibles")
                        .HasColumnType("integer");

                    b.Property<int>("CantidadClientes")
                        .HasColumnType("integer");

                    b.Property<decimal>("Costo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime");

                    b.Property<int>("idPelicula")
                        .HasColumnType("integer");

                    b.Property<int>("idSala")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("idPelicula");

                    b.HasIndex("idSala");

                    b.ToTable("Funciones", (string)null);

                    b.HasData(
                        new
                        {
                            ID = 1,
                            AsientosDisponibles = 200,
                            CantidadClientes = 0,
                            Costo = 2000m,
                            Fecha = new DateTime(1992, 11, 2, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            idPelicula = 1,
                            idSala = 1
                        },
                        new
                        {
                            ID = 2,
                            AsientosDisponibles = 150,
                            CantidadClientes = 0,
                            Costo = 2500m,
                            Fecha = new DateTime(1992, 11, 2, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            idPelicula = 2,
                            idSala = 1
                        },
                        new
                        {
                            ID = 3,
                            AsientosDisponibles = 250,
                            CantidadClientes = 0,
                            Costo = 1500m,
                            Fecha = new DateTime(1992, 11, 2, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            idPelicula = 2,
                            idSala = 2
                        },
                        new
                        {
                            ID = 4,
                            AsientosDisponibles = 175,
                            CantidadClientes = 0,
                            Costo = 1000m,
                            Fecha = new DateTime(1992, 11, 2, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            idPelicula = 2,
                            idSala = 2
                        },
                        new
                        {
                            ID = 5,
                            AsientosDisponibles = 300,
                            CantidadClientes = 0,
                            Costo = 2200m,
                            Fecha = new DateTime(1992, 11, 2, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            idPelicula = 3,
                            idSala = 2
                        },
                        new
                        {
                            ID = 6,
                            AsientosDisponibles = 300,
                            CantidadClientes = 0,
                            Costo = 2200m,
                            Fecha = new DateTime(1992, 11, 2, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            idPelicula = 3,
                            idSala = 2
                        },
                        new
                        {
                            ID = 7,
                            AsientosDisponibles = 200,
                            CantidadClientes = 0,
                            Costo = 1800m,
                            Fecha = new DateTime(1992, 11, 2, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            idPelicula = 3,
                            idSala = 3
                        },
                        new
                        {
                            ID = 8,
                            AsientosDisponibles = 180,
                            CantidadClientes = 0,
                            Costo = 1500m,
                            Fecha = new DateTime(1992, 11, 2, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            idPelicula = 4,
                            idSala = 3
                        },
                        new
                        {
                            ID = 9,
                            AsientosDisponibles = 250,
                            CantidadClientes = 0,
                            Costo = 1200m,
                            Fecha = new DateTime(1992, 11, 2, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            idPelicula = 4,
                            idSala = 4
                        },
                        new
                        {
                            ID = 10,
                            AsientosDisponibles = 175,
                            CantidadClientes = 0,
                            Costo = 1000m,
                            Fecha = new DateTime(1992, 11, 2, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            idPelicula = 4,
                            idSala = 4
                        },
                        new
                        {
                            ID = 11,
                            AsientosDisponibles = 300,
                            CantidadClientes = 0,
                            Costo = 2000m,
                            Fecha = new DateTime(1992, 11, 2, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            idPelicula = 4,
                            idSala = 1
                        },
                        new
                        {
                            ID = 12,
                            AsientosDisponibles = 280,
                            CantidadClientes = 0,
                            Costo = 2200m,
                            Fecha = new DateTime(1992, 11, 2, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            idPelicula = 1,
                            idSala = 1
                        },
                        new
                        {
                            ID = 13,
                            AsientosDisponibles = 220,
                            CantidadClientes = 0,
                            Costo = 1900m,
                            Fecha = new DateTime(1992, 11, 2, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            idPelicula = 2,
                            idSala = 2
                        },
                        new
                        {
                            ID = 14,
                            AsientosDisponibles = 190,
                            CantidadClientes = 0,
                            Costo = 1700m,
                            Fecha = new DateTime(1992, 11, 2, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            idPelicula = 3,
                            idSala = 2
                        },
                        new
                        {
                            ID = 15,
                            AsientosDisponibles = 230,
                            CantidadClientes = 0,
                            Costo = 1400m,
                            Fecha = new DateTime(1992, 11, 2, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            idPelicula = 2,
                            idSala = 3
                        },
                        new
                        {
                            ID = 16,
                            AsientosDisponibles = 200,
                            CantidadClientes = 0,
                            Costo = 1200m,
                            Fecha = new DateTime(1992, 11, 2, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            idPelicula = 1,
                            idSala = 3
                        },
                        new
                        {
                            ID = 17,
                            AsientosDisponibles = 250,
                            CantidadClientes = 0,
                            Costo = 1000m,
                            Fecha = new DateTime(1992, 11, 2, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            idPelicula = 2,
                            idSala = 4
                        },
                        new
                        {
                            ID = 18,
                            AsientosDisponibles = 300,
                            CantidadClientes = 0,
                            Costo = 2200m,
                            Fecha = new DateTime(1992, 11, 2, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            idPelicula = 2,
                            idSala = 4
                        },
                        new
                        {
                            ID = 19,
                            AsientosDisponibles = 270,
                            CantidadClientes = 0,
                            Costo = 1900m,
                            Fecha = new DateTime(1992, 11, 2, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            idPelicula = 3,
                            idSala = 1
                        },
                        new
                        {
                            ID = 20,
                            AsientosDisponibles = 230,
                            CantidadClientes = 0,
                            Costo = 1700m,
                            Fecha = new DateTime(1992, 11, 2, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            idPelicula = 4,
                            idSala = 1
                        },
                        new
                        {
                            ID = 21,
                            AsientosDisponibles = 190,
                            CantidadClientes = 0,
                            Costo = 1400m,
                            Fecha = new DateTime(2023, 11, 2, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            idPelicula = 1,
                            idSala = 2
                        });
                });

            modelBuilder.Entity("TP1___GRUPO_C.Model.Pelicula", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<int>("Duracion")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Poster")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Sinopsis")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("ID");

                    b.ToTable("Peliculas", (string)null);

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Descripcion = "Un juguete",
                            Duracion = 2,
                            Nombre = "Toy Story",
                            Poster = "",
                            Sinopsis = "Uno"
                        },
                        new
                        {
                            ID = 2,
                            Descripcion = "Un juguete 2",
                            Duracion = 2,
                            Nombre = "Toy Story 2",
                            Poster = "",
                            Sinopsis = "Dos"
                        },
                        new
                        {
                            ID = 3,
                            Descripcion = "Un juguete 3",
                            Duracion = 2,
                            Nombre = "Toy Story 3",
                            Poster = "",
                            Sinopsis = "Tres"
                        },
                        new
                        {
                            ID = 4,
                            Descripcion = "Basta de la misma pelicula",
                            Duracion = 2,
                            Nombre = "Toy Story 4",
                            Poster = "",
                            Sinopsis = "Cuatro"
                        });
                });

            modelBuilder.Entity("TP1___GRUPO_C.Model.Sala", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("Capacidad")
                        .HasColumnType("integer");

                    b.Property<string>("Ubicacion")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("ID");

                    b.ToTable("Salas", (string)null);

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Capacidad = 100,
                            Ubicacion = "Olivos"
                        },
                        new
                        {
                            ID = 2,
                            Capacidad = 200,
                            Ubicacion = "San Isidro"
                        },
                        new
                        {
                            ID = 3,
                            Capacidad = 500,
                            Ubicacion = "Caballito"
                        },
                        new
                        {
                            ID = 4,
                            Capacidad = 300,
                            Ubicacion = "Palermo"
                        },
                        new
                        {
                            ID = 5,
                            Capacidad = 150,
                            Ubicacion = "Recoleta"
                        },
                        new
                        {
                            ID = 6,
                            Capacidad = 100,
                            Ubicacion = "Belgrano"
                        },
                        new
                        {
                            ID = 7,
                            Capacidad = 200,
                            Ubicacion = "La Plata"
                        },
                        new
                        {
                            ID = 8,
                            Capacidad = 150,
                            Ubicacion = "Mar del Plata"
                        },
                        new
                        {
                            ID = 9,
                            Capacidad = 120,
                            Ubicacion = "Córdoba"
                        },
                        new
                        {
                            ID = 10,
                            Capacidad = 200,
                            Ubicacion = "Rosario"
                        },
                        new
                        {
                            ID = 11,
                            Capacidad = 130,
                            Ubicacion = "Mendoza"
                        },
                        new
                        {
                            ID = 12,
                            Capacidad = 150,
                            Ubicacion = "Tigre"
                        },
                        new
                        {
                            ID = 13,
                            Capacidad = 200,
                            Ubicacion = "Quilmes"
                        },
                        new
                        {
                            ID = 14,
                            Capacidad = 170,
                            Ubicacion = "San Miguel"
                        },
                        new
                        {
                            ID = 15,
                            Capacidad = 180,
                            Ubicacion = "Lomas de Zamora"
                        },
                        new
                        {
                            ID = 16,
                            Capacidad = 200,
                            Ubicacion = "Morón"
                        },
                        new
                        {
                            ID = 17,
                            Capacidad = 120,
                            Ubicacion = "Avellaneda"
                        },
                        new
                        {
                            ID = 18,
                            Capacidad = 110,
                            Ubicacion = "Banfield"
                        },
                        new
                        {
                            ID = 19,
                            Capacidad = 1,
                            Ubicacion = "E.T. el Extraterrestre"
                        });
                });

            modelBuilder.Entity("TP1___GRUPO_C.Model.Usuario", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("Bloqueado")
                        .HasColumnType("bit");

                    b.Property<decimal>("Credito")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("DNI")
                        .HasColumnType("bigint");

                    b.Property<bool>("EsAdmin")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime");

                    b.Property<int>("IntentosFallidos")
                        .HasColumnType("int");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("ID");

                    b.ToTable("Usuarios", (string)null);

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Apellido = "Perez",
                            Bloqueado = false,
                            Credito = 100m,
                            DNI = 1111111L,
                            EsAdmin = false,
                            FechaNacimiento = new DateTime(1992, 11, 2, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            IntentosFallidos = 0,
                            Mail = "pepe@mail.com",
                            Nombre = "Pepe",
                            Password = "123"
                        },
                        new
                        {
                            ID = 2,
                            Apellido = "Admin",
                            Bloqueado = false,
                            Credito = 0m,
                            DNI = 2222222L,
                            EsAdmin = true,
                            FechaNacimiento = new DateTime(1990, 6, 8, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            IntentosFallidos = 0,
                            Mail = "admin@mail.com",
                            Nombre = "El",
                            Password = "123"
                        },
                        new
                        {
                            ID = 3,
                            Apellido = "Rodriguez",
                            Bloqueado = false,
                            Credito = 3000m,
                            DNI = 3333333L,
                            EsAdmin = false,
                            FechaNacimiento = new DateTime(1995, 8, 24, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            IntentosFallidos = 0,
                            Mail = "lucas@mail.com",
                            Nombre = "Lucas",
                            Password = "123"
                        },
                        new
                        {
                            ID = 4,
                            Apellido = "González",
                            Bloqueado = false,
                            Credito = 500m,
                            DNI = 4444444L,
                            EsAdmin = false,
                            FechaNacimiento = new DateTime(1988, 5, 15, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            IntentosFallidos = 0,
                            Mail = "ana@mail.com",
                            Nombre = "Ana",
                            Password = "123"
                        },
                        new
                        {
                            ID = 5,
                            Apellido = "López",
                            Bloqueado = false,
                            Credito = 200m,
                            DNI = 5555555L,
                            EsAdmin = false,
                            FechaNacimiento = new DateTime(1993, 9, 30, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            IntentosFallidos = 0,
                            Mail = "maria@mail.com",
                            Nombre = "María",
                            Password = "123"
                        },
                        new
                        {
                            ID = 6,
                            Apellido = "Fernández",
                            Bloqueado = false,
                            Credito = 800m,
                            DNI = 666666L,
                            EsAdmin = false,
                            FechaNacimiento = new DateTime(1994, 12, 10, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            IntentosFallidos = 0,
                            Mail = "luis@mail.com",
                            Nombre = "Luis",
                            Password = "123"
                        },
                        new
                        {
                            ID = 7,
                            Apellido = "Martínez",
                            Bloqueado = false,
                            Credito = 1500m,
                            DNI = 77777777L,
                            EsAdmin = false,
                            FechaNacimiento = new DateTime(1991, 7, 18, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            IntentosFallidos = 0,
                            Mail = "laura@mail.com",
                            Nombre = "Laura",
                            Password = "123"
                        },
                        new
                        {
                            ID = 8,
                            Apellido = "Gómez",
                            Bloqueado = false,
                            Credito = 1200m,
                            DNI = 88888888L,
                            EsAdmin = false,
                            FechaNacimiento = new DateTime(1996, 3, 25, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            IntentosFallidos = 0,
                            Mail = "carlos@mail.com",
                            Nombre = "Carlos",
                            Password = "123"
                        },
                        new
                        {
                            ID = 9,
                            Apellido = "Rodríguez",
                            Bloqueado = false,
                            Credito = 2500m,
                            DNI = 999999L,
                            EsAdmin = false,
                            FechaNacimiento = new DateTime(1989, 9, 12, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            IntentosFallidos = 0,
                            Mail = "ana.rodriguez@mail.com",
                            Nombre = "Ana",
                            Password = "123"
                        },
                        new
                        {
                            ID = 10,
                            Apellido = "López",
                            Bloqueado = false,
                            Credito = 300m,
                            DNI = 1000000L,
                            EsAdmin = false,
                            FechaNacimiento = new DateTime(1997, 11, 28, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            IntentosFallidos = 0,
                            Mail = "marcelo@mail.com",
                            Nombre = "Marcelo",
                            Password = "123"
                        },
                        new
                        {
                            ID = 11,
                            Apellido = "Torres",
                            Bloqueado = false,
                            Credito = 1800m,
                            DNI = 1112111L,
                            EsAdmin = false,
                            FechaNacimiento = new DateTime(1993, 2, 4, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            IntentosFallidos = 0,
                            Mail = "julia@mail.com",
                            Nombre = "Julia",
                            Password = "123"
                        },
                        new
                        {
                            ID = 12,
                            Apellido = "García",
                            Bloqueado = false,
                            Credito = 5000m,
                            DNI = 12321312L,
                            EsAdmin = false,
                            FechaNacimiento = new DateTime(1995, 6, 22, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            IntentosFallidos = 0,
                            Mail = "mariano@mail.com",
                            Nombre = "Mariano",
                            Password = "123"
                        },
                        new
                        {
                            ID = 13,
                            Apellido = "López",
                            Bloqueado = false,
                            Credito = 700m,
                            DNI = 312312312L,
                            EsAdmin = false,
                            FechaNacimiento = new DateTime(1990, 10, 8, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            IntentosFallidos = 0,
                            Mail = "gabriela@mail.com",
                            Nombre = "Gabriela",
                            Password = "123"
                        },
                        new
                        {
                            ID = 14,
                            Apellido = "Pérez",
                            Bloqueado = false,
                            Credito = 1000m,
                            DNI = 3123123L,
                            EsAdmin = false,
                            FechaNacimiento = new DateTime(1994, 4, 16, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            IntentosFallidos = 0,
                            Mail = "federico@mail.com",
                            Nombre = "Federico",
                            Password = "123"
                        },
                        new
                        {
                            ID = 15,
                            Apellido = "Fernández",
                            Bloqueado = false,
                            Credito = 250m,
                            DNI = 312312L,
                            EsAdmin = false,
                            FechaNacimiento = new DateTime(1991, 8, 14, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            IntentosFallidos = 0,
                            Mail = "carolina@mail.com",
                            Nombre = "Carolina",
                            Password = "123"
                        },
                        new
                        {
                            ID = 16,
                            Apellido = "González",
                            Bloqueado = false,
                            Credito = 3500m,
                            DNI = 2141241L,
                            EsAdmin = false,
                            FechaNacimiento = new DateTime(1988, 12, 30, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            IntentosFallidos = 0,
                            Mail = "luciana@mail.com",
                            Nombre = "Luciana",
                            Password = "123"
                        },
                        new
                        {
                            ID = 17,
                            Apellido = "Martínez",
                            Bloqueado = false,
                            Credito = 900m,
                            DNI = 321312L,
                            EsAdmin = false,
                            FechaNacimiento = new DateTime(1997, 3, 17, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            IntentosFallidos = 0,
                            Mail = "martin@mail.com",
                            Nombre = "Martín",
                            Password = "123"
                        },
                        new
                        {
                            ID = 18,
                            Apellido = "Gómez",
                            Bloqueado = false,
                            Credito = 2000m,
                            DNI = 412123L,
                            EsAdmin = false,
                            FechaNacimiento = new DateTime(1992, 9, 24, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            IntentosFallidos = 0,
                            Mail = "paula@mail.com",
                            Nombre = "Paula",
                            Password = "123"
                        },
                        new
                        {
                            ID = 19,
                            Apellido = "Rodríguez",
                            Bloqueado = false,
                            Credito = 3000m,
                            DNI = 421321L,
                            EsAdmin = false,
                            FechaNacimiento = new DateTime(1996, 1, 11, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            IntentosFallidos = 0,
                            Mail = "diego.rodriguez@mail.com",
                            Nombre = "Diego",
                            Password = "123"
                        },
                        new
                        {
                            ID = 20,
                            Apellido = "López",
                            Bloqueado = false,
                            Credito = 600m,
                            DNI = 421412L,
                            EsAdmin = false,
                            FechaNacimiento = new DateTime(1993, 5, 28, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            IntentosFallidos = 0,
                            Mail = "sofia@mail.com",
                            Nombre = "Sofía",
                            Password = "123"
                        },
                        new
                        {
                            ID = 21,
                            Apellido = "Torres",
                            Bloqueado = false,
                            Credito = 1400m,
                            DNI = 412412L,
                            EsAdmin = false,
                            FechaNacimiento = new DateTime(1989, 11, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            IntentosFallidos = 0,
                            Mail = "agustin@mail.com",
                            Nombre = "Agustín",
                            Password = "123"
                        });
                });

            modelBuilder.Entity("TP1___GRUPO_C.Modelos.UsuarioFuncion", b =>
                {
                    b.Property<int>("idUsuario")
                        .HasColumnType("integer");

                    b.Property<int>("idFuncion")
                        .HasColumnType("integer");

                    b.Property<int>("CantidadEntradasCompradas")
                        .HasColumnType("integer");

                    b.HasKey("idUsuario", "idFuncion");

                    b.HasIndex("idFuncion");

                    b.ToTable("UF");

                    b.HasData(
                        new
                        {
                            idUsuario = 1,
                            idFuncion = 1,
                            CantidadEntradasCompradas = 1
                        },
                        new
                        {
                            idUsuario = 1,
                            idFuncion = 2,
                            CantidadEntradasCompradas = 4
                        },
                        new
                        {
                            idUsuario = 1,
                            idFuncion = 3,
                            CantidadEntradasCompradas = 1
                        },
                        new
                        {
                            idUsuario = 3,
                            idFuncion = 4,
                            CantidadEntradasCompradas = 3
                        },
                        new
                        {
                            idUsuario = 3,
                            idFuncion = 5,
                            CantidadEntradasCompradas = 2
                        },
                        new
                        {
                            idUsuario = 4,
                            idFuncion = 9,
                            CantidadEntradasCompradas = 2
                        },
                        new
                        {
                            idUsuario = 4,
                            idFuncion = 10,
                            CantidadEntradasCompradas = 4
                        },
                        new
                        {
                            idUsuario = 4,
                            idFuncion = 11,
                            CantidadEntradasCompradas = 2
                        },
                        new
                        {
                            idUsuario = 6,
                            idFuncion = 12,
                            CantidadEntradasCompradas = 3
                        },
                        new
                        {
                            idUsuario = 6,
                            idFuncion = 13,
                            CantidadEntradasCompradas = 1
                        },
                        new
                        {
                            idUsuario = 6,
                            idFuncion = 14,
                            CantidadEntradasCompradas = 4
                        },
                        new
                        {
                            idUsuario = 8,
                            idFuncion = 15,
                            CantidadEntradasCompradas = 2
                        },
                        new
                        {
                            idUsuario = 8,
                            idFuncion = 16,
                            CantidadEntradasCompradas = 3
                        },
                        new
                        {
                            idUsuario = 8,
                            idFuncion = 17,
                            CantidadEntradasCompradas = 1
                        },
                        new
                        {
                            idUsuario = 10,
                            idFuncion = 18,
                            CantidadEntradasCompradas = 4
                        },
                        new
                        {
                            idUsuario = 10,
                            idFuncion = 19,
                            CantidadEntradasCompradas = 2
                        },
                        new
                        {
                            idUsuario = 10,
                            idFuncion = 20,
                            CantidadEntradasCompradas = 3
                        });
                });

            modelBuilder.Entity("TP1___GRUPO_C.Model.Funcion", b =>
                {
                    b.HasOne("TP1___GRUPO_C.Model.Pelicula", "MiPelicula")
                        .WithMany("MisFunciones")
                        .HasForeignKey("idPelicula")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TP1___GRUPO_C.Model.Sala", "MiSala")
                        .WithMany("MisFunciones")
                        .HasForeignKey("idSala")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MiPelicula");

                    b.Navigation("MiSala");
                });

            modelBuilder.Entity("TP1___GRUPO_C.Modelos.UsuarioFuncion", b =>
                {
                    b.HasOne("TP1___GRUPO_C.Model.Funcion", "funcion")
                        .WithMany("UserFuncion")
                        .HasForeignKey("idFuncion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TP1___GRUPO_C.Model.Usuario", "usuario")
                        .WithMany("UserFuncion")
                        .HasForeignKey("idUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("funcion");

                    b.Navigation("usuario");
                });

            modelBuilder.Entity("TP1___GRUPO_C.Model.Funcion", b =>
                {
                    b.Navigation("UserFuncion");
                });

            modelBuilder.Entity("TP1___GRUPO_C.Model.Pelicula", b =>
                {
                    b.Navigation("MisFunciones");
                });

            modelBuilder.Entity("TP1___GRUPO_C.Model.Sala", b =>
                {
                    b.Navigation("MisFunciones");
                });

            modelBuilder.Entity("TP1___GRUPO_C.Model.Usuario", b =>
                {
                    b.Navigation("UserFuncion");
                });
#pragma warning restore 612, 618
        }
    }
}
